### PR TITLE
Create function preview markdown

### PR DESCRIPTION
**Pull request by kztera**
- Create function preview():

```js
function preview() {
    var markdownText = document.getElementById('textarea').value;
    document.getElementById('preview').innerHTML = marked.parse(markdownText);
}
```

- I noticed there was a problem with responsive of web when zoom in or zoom out and preview. We need more time to fix it.
- When the interface is better, we will perform the Live preview function instead of having to press preview every time. Thanks for reading this far xD

### CODE REVIEW

**Comment by kztera** [comment]
Oh, I'm sorry because of Prettier auto format on save. It has made the JS file seem like it has changed a lot :(( I think we need a setting file of prettier for this 💯 Expect this from you

**Comment by WillDev12** [comment]
> Oh, I'm sorry because of Prettier auto format on save. It has made the JS file seem like it has changed a lot :(( I think we need a setting file of prettier for this 💯 Expect this from you

Don’t worry you’ve been absolutely awesome with this!  I’m kind of new to GitHub how exactly would I make a setting file? Anyways thank you very much for the help.

**Comment by kztera** [comment]
> > Oh, I'm sorry because of Prettier auto format on save. It has made the JS file seem like it has changed a lot :(( I think we need a setting file of prettier for this 💯 Expect this from you
> 
> Don’t worry you’ve been absolutely awesome with this! I’m kind of new to GitHub how exactly would I make a setting file? Anyways thank you very much for the help.

Do u use Prettier to format your code? A config file for Prettier will be a general standard so that when we format the code, we get the same format

You can read more about the config file in [here](https://prettier.io/docs/en/configuration.html) ^^

**Comment by WillDev12** [comment]
Wow I’m haven’t heard of that yet.  I will do some research so that this can be taken care of.  

> > > Oh, I'm sorry because of Prettier auto format on save. It has made the JS file seem like it has changed a lot :(( I think we need a setting file of prettier for this 💯 Expect this from you
> > 
> > 
> > Don’t worry you’ve been absolutely awesome with this! I’m kind of new to GitHub how exactly would I make a setting file? Anyways thank you very much for the help.
> 
> Do u use Prettier to format your code? A config file for Prettier will be a general standard so that when we format the code, we get the same format
> 
> You can read more about the config file in [here](https://prettier.io/docs/en/configuration.html) ^^

Wow I haven’t heard of that yet.  I will do some research so that I can get this taken care of.  If you have any more info on this please tell me.  Again, thanks for the awesome support!

**Comment by kztera** [comment]
> Wow I haven’t heard of that yet. I will do some research so that I can get this taken care of. If you have any more info on this please tell me. Again, thanks for the awesome support!

Hmmm, let me help you create it :>

**Comment by WillDev12** [comment]
> Hmmm, let me help you create it :>

Thanks a lot I’m newer to web development and really development in general so the help is really appreciated.

**Comment by kztera** [comment]
> Thanks a lot I’m newer to web development and really development in general so the help is really appreciated.

The fact that I am also a newbie xD I have learned many new things since trying to contribute to your project. If you pay attention to my repositories, I really haven't had any specific projects yet. ;-;

**Comment by WillDev12** [comment]
> The fact that I am also a newbie xD I have learned many new things since trying to contribute to your project. If you pay attention to my repositories, I really haven't had any specific projects yet. ;-;

Ha, yeah I’ve also learned a whole lot from this too.   It’s cool what you can learn from stuff like this lol.  The way I find ideas for projects is I just constantly look for simple things that I can automate while coding.  I’ve sure learned plenty over the couple months I have been active.

**Comment by kztera** [comment]
> > The fact that I am also a newbie xD I have learned many new things since trying to contribute to your project. If you pay attention to my repositories, I really haven't had any specific projects yet. ;-;
> 
> Ha, yeah I’ve also learned a whole lot from this too.   It’s cool what you can learn from stuff like this lol.  The way I find ideas for projects is I just constantly look for simple things that I can automate while coding.  I’ve sure learned plenty over the couple months I have been active.
>  The biggest reason I stopped seeing your project is because I can understand a little bit lol.  Really looking forward to your next projects.  Or maybe it's a joint project between you and me.  Who knows, XD In real life, it's a pity that I don't have anyone to study with ;-; Sometimes it makes me so lazy 🥲 It's fun to chat with you today xD I'm going to bed first.  It's already 2 a.m. on April 2 where I am 🤣

**Comment by WillDev12** [comment]
> > > The fact that I am also a newbie xD I have learned many new things since trying to contribute to your project. If you pay attention to my repositories, I really haven't had any specific projects yet. ;-;
> > 
> > 
> > Ha, yeah I’ve also learned a whole lot from this too.   It’s cool what you can learn from stuff like this lol.  The way I find ideas for projects is I just constantly look for simple things that I can automate while coding.  I’ve sure learned plenty over the couple months I have been active.
> 
> The biggest reason I stopped seeing your project is because I can understand a little bit lol. Really looking forward to your next projects. Or maybe it's a joint project between you and me. Who knows, XD In real life, it's a pity that I don't have anyone to study with ;-; Sometimes it makes me so lazy 🥲 It's fun to chat with you today xD I'm going to bed first. It's already 2 a.m. on April 2 where I am 🤣

I’m in similar conditions only midday 🤣.  I’m pretty much self taught so I’m a bit slow with things like this lol.  Anyways I’d be happy to help with a collaboration as far as what I can understand about it :).  Fun chat have a nice one!

**Pull request merged**
